pipeline {
    agent any    
    environment {
        registry = 'python-app'
        registryCredential = 'acrjenkins'
        registryUrl = 'acrjenkins.azurecr.io'
        dockerImage = ''
    }

    stages{
        stage ('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cgmartinezceron/jenkins.git']]])
            }
        }

        // Building Docker images
        stage('Building image') {
            steps{
                script {
                    dir("dockertoacr"){
                        dockerImage = docker.build registry
                    }
                    
                }
            }
        }

        // Uploading Docker images into ACR
        stage('Upload Image to ACR') {
            steps{    
                script {
                    docker.withRegistry( "http://${registryUrl}", registryCredential ) {
                    dockerImage.push()
                    }
                }
            }
        }

        stage ('K8S Deploy') {
            steps {
                script {
                    dir("dockertoacr"){
                        kubernetesDeploy(
                            configs: 'k8s-deployment.yaml',
                            kubeconfigId: 'aks',
                            enableConfigSubstitution: false
                            )
                    }
                }
            }
        }
    }
}