pipeline {
    agent any    
    environment {
        registryname = 'acrjenkins'
    }

    stages{
        stage ('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cgmartinezceron/jenkins.git']]])
            }
        }
        // Building Docker images
        stage('Building image') {
            steps{
                sh '''
                docker build -t acrjenkins .
                '''
            }
        }
    }
}